Repository argon1025/Tilog-client, pull requests merged in 2021-12, with the labels that each got.

#28 TIL-159 comment 부분 수정 완료
  package-lock.json
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostComment.component copy/PostComment.component.js
  src/Components/PostComment.component copy/slave.components/Comment.slave.component.js
  src/Components/PostComment.component copy/slave.components/CommentToComment.slave.component.js
  src/Components/PostComment.component copy/slave.components/InputComment.slave.component.js
  src/Components/PostComment.component copy/slave.components/InputCommentToComment.slave.component.js
  src/Components/PostComment.component copy/slave.components/RenderComments.slave.component.js
  src/Components/PostComment.component copy/slave.components/updateComment.slave.component.js
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comment.slave.component.js
  src/Components/PostComment.component/slave.components/CommentToComment.slave.component.js
  src/Components/PostComment.component/slave.components/InputComment.slave.component.js
  src/Components/PostComment.component/slave.components/InputCommentToComment.slave.component.js
  src/Components/PostComment.component/slave.components/RenderComment.slave.component.js
  src/Components/PostComment.component/slave.components/RenderCommentTools.slave.component.js
  src/Components/PostComment.component/slave.components/RenderComments.slave.component.js
  src/Components/PostComment.component/slave.components/RenderInputComment.slave.component.js
  src/Components/PostComment.component/slave.components/updateComment.slave.component.js
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/AddStopModal.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/utilities/api/TILog/comments.js
  src/utilities/api/index.js
  src/utilities/hooks/comments/useComments.js
  src/utilities/hooks/comments/useViewComments.js
Labels: enhancement

#29 Til 169
  public/css/style.css
  src/Components/Introduce.component/Introduce.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/UserBlog.component/slave.components/Activity/UserActivity.slave.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
Labels: bug

#31 Til 148 이미지 드래그 앤 드롭 업로드
  package-lock.json
  package.json
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Header/PostHeader.slave.component.js
  src/Components/PostDetail.component/slave.components/MarkdownViewer/MarkdownViewer.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  yarn.lock
Labels: enhancement

#32 TIL-159 버그 수정
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/RenderCommentTools.slave.component.js
  src/Components/PostComment.component/slave.components/RenderComments.slave.component.js
  src/Components/PostComment.component/slave.components/RenderInputComment.slave.component.js
  src/Components/PostComment.component/slave.components/RenderReplies.slave.component.js
Labels: enhancement

#33 Til 173
  package-lock.json
  package.json
  postcss.config.js
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
  src/Components/PostDetail.component/slave.components/MarkdownViewer/MarkdownViewer.slave.component.js
  yarn.lock
Labels: enhancement

#34 TIL-159 일부 버그 수정 및 주석추가 comment관련 경고 제거
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Comments/InputComment.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/RenderCommentTools.slave.component.js
  src/Components/PostComment.component/slave.components/RenderComments.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/InputReply.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/utilities/hooks/comments/useComments.js
  src/utilities/hooks/comments/useReplies.js
  src/utilities/hooks/index.js
Labels: bug

#35 Til 174 포스트 뷰, 네비바 디자인 개선
  public/index.html
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Header/PostHeader.slave.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/Utility.components/techIconLoader.js
  src/Components/index.js
  tailwind.config.js
Labels: enhancement

#36 Modify 댓글 디자인 수정
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/InputReply.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostDetail.component/PostDetail.component.js
Labels: enhancement

#38 Modify PostList 디자인 수정
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
Labels: enhancement

#39 Til 149
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/AddStopModal.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/slave.components/Activity/UserActivity.slave.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
Labels: enhancement

#40 TIL-159 토스트 메세지 추가
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/utilities/hooks/comments/useComments.js
  src/utilities/hooks/comments/useReplies.js
Labels: enhancement

#41 TIL-159 로그인 관련 버그 수정
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
Labels: bug

#42 Til 185
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/UserBlog.component/slave.components/Activity/UserActivity.slave.component.js
  src/Components/UserBlog.component/slave.components/NotFound/NotFound.salve.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
  src/Redux/action/authActions.js
  src/Redux/action/index.js
  src/Redux/reducer/authReducers.js
  src/index.js
  src/utilities/api/TILog/auth.js
  src/utilities/api/TILog/core/index.js
  src/utilities/api/TILog/posts.js
  src/utilities/api/TILog/users.js
  src/utilities/api/github-stats/core/index.js
  src/utilities/api/index.js
  src/utilities/hooks/comments/useComments.js
  src/utilities/hooks/github/useUserPinnedRepo.js
  src/utilities/hooks/github/useUserStats.js
  src/utilities/hooks/github/useUserTopLanguage.js
  src/utilities/hooks/github/useWeeklyStats.js
  src/utilities/hooks/index.js
  src/utilities/hooks/posts/useAllFindByUserID.js
  src/utilities/hooks/posts/useLike.js
  src/utilities/hooks/posts/useViewCursorPost.js
  src/utilities/hooks/users/useUserInfo.js
  src/utilities/hooks/users/useUserInfoToUserName.js
Labels: bug, enhancement
