Repository argon1025/Tilog-client, pull requests merged in 2022-01, with the labels that each got.

#43 Til 192
  src/Components/Header.component/Header.component.js
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Header.component/slave.components/UserBlog.slave.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/LikeButton/LikeButton.slave.component.js
  src/Components/PostDetail.component/slave.components/MarkdownViewer/MarkdownViewer.slave.component.js
  src/Components/PostDetail.component/slave.components/Tags/Tags.slave.component.js
  src/Components/PostDetail.component/slave.components/ThumbNail/ThumbNail.slave.component.js
  src/Components/PostDetail.component/slave.components/Title/Title.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/UserBlog.component/slave.components/NotFound/NotFound.salve.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
  src/index.js
  src/utilities/hooks/posts/useViewDetailPost.js
Labels: bug, documentation, enhancement

#45 Skeleton Components
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/ArticleSkeleton.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/Components/UserBlog.component/slave.components/StatsSkeleton.slave.component.js
Labels: enhancement

#46 포스트 에디터 스타일 변경
  public/css/style.css
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Containers/PostCreate.container/PostCreate.container.js
Labels: enhancement

#47 배포전 디자인 수정
  src/Components/Header.component/Header.component.js
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
Labels: enhancement

#48 Til 196
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/utilities/api/TILog/core/index.js
  src/utilities/api/github-stats/core/index.js
  src/utilities/hooks/github/useUserPinnedRepo.js
  src/utilities/hooks/github/useUserStats.js
  src/utilities/hooks/github/useUserTopLanguage.js
  src/utilities/hooks/posts/useViewCursorPost.js
  src/utilities/hooks/users/useUserInfoToUserName.js
Labels: bug, documentation

#49 Fix 이미지 업로드시 에디터 멈춤현상 해결
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
Labels: bug

#50 Modify 모바일, 사파리 대응 및 세부 디자인 수정
  public/css/style.css
  public/index.html
  src/Components/Header.component/Header.component.js
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Header.component/slave.components/UserBlog.slave.component.js
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/Tags/Tags.slave.component.js
  src/Components/PostDetail.component/slave.components/Title/Title.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
  src/Components/Utility.components/TechIconList.js
  tailwind.config.js
Labels: enhancement

#51 Helmet, 메타데이터 추가
  package.json
  public/favicon.ico
  public/index.html
  public/logo.svg
  public/logo128.png
  public/logo192.png
  public/logo256.png
  public/logo512.png
  public/logo65.png
  public/manifest.json
  public/ogImage.png
  src/Components/Helmet.component/Helmet.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/UserBlog.component/UserBlog.component.js
  src/Components/index.js
  src/index.js
  yarn.lock
Labels: enhancement

#52 HotFix Paste Image Upload
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
Labels: bug

#54 Til 202
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Comments/InputComment.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/InputReply.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/utilities/api/TILog/core/index.js
  src/utilities/api/github-stats/core/index.js
  src/utilities/hooks/comments/useCommentTools.js
  src/utilities/hooks/comments/useComments.js
  src/utilities/hooks/comments/useReplies.js
  src/utilities/hooks/github/useUserPinnedRepo.js
  src/utilities/hooks/github/useUserStats.js
  src/utilities/hooks/github/useUserTopLanguage.js
  src/utilities/hooks/index.js
  src/utilities/hooks/posts/useViewCursorPost.js
  src/utilities/hooks/posts/useViewDetailPost.js
  src/utilities/hooks/users/useUserInfoToUserName.js
Labels: bug, documentation, enhancement

#55 TIL-207 좋아요 구현
  src/Components/PostDetail.component/PostDetail.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/LikeButton/LikeButton.slave.component.js
  src/utilities/hooks/comments/useCommentTools.js
  src/utilities/hooks/posts/useLike.js
  src/utilities/hooks/posts/useViewDetailPost.js
Labels: enhancement

#56 댓글, 좋아요 컴포넌트 디자인개선
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Comments/InputComment.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/InputReply.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/LikeButton/LikeButton.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/index.js
Labels: enhancement

#57 Til 210
  src/Components/Introduce.component/TrendPosts.slave.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/Skeleton/ArticleSkeleton.slave.component.js
  src/Components/PostDetail.component/slave.components/Title/Title.slave.component.js
  src/Components/Test.component/Test.component.js
  src/Components/UserBlog.component/slave.components/Skeleton/StatsSkeleton.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/Components/index.js
  src/Containers/Test.container/Test.container.js
  src/Containers/index.js
  src/utilities/api/TILog/posts.js
  src/utilities/hooks/posts/useDeletePost.js
  src/utilities/hooks/posts/useTrendPosts.js
  src/utilities/hooks/posts/useViewCursorPost.js
Labels: bug, documentation, enhancement

#58 Add 메인페이지 디자인 변경 및 포스트 카드 추가
  src/Components/Introduce.component/Introduce.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRank.slave.component.js
Labels: enhancement

#60 Til 211 로그인관련 수정
  src/Components/Introduce.component/Introduce.component.js
  src/Components/Login.component/Login.component.js
  src/Components/PostModify.component/PostModify.component.js
  src/Components/PostModify.component/slave.components/AddStopModal.slave.component.js
  src/Components/PostModify.component/slave.components/Editor.slave.component.js
  src/Components/PostModify.component/slave.components/Loading.slave.component.js
  src/Components/PostModify.component/slave.components/MenuBar.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/index.js
  src/Containers/Login.container/Login.container.js
  src/Containers/index.js
  src/Redux/action/authActions.js
  src/index.js
  src/utilities/hooks/comments/useCommentTools.js
  src/utilities/hooks/comments/useReplies.js
  src/utilities/hooks/posts/useDeletePost.js
  src/utilities/hooks/posts/useLike.js
Labels: bug, documentation

#61 Modify 인기 게시글 디자인 변경
  src/Components/Introduce.component/Introduce.component.js
  src/Components/Introduce.component/TrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRank.slave.component.js
Labels: enhancement

#62 TIl-216 트랜드 기간 수정
  src/Components/Introduce.component/Introduce.component.js
  src/Components/Introduce.component/TrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRank.slave.component.js
  src/Components/Introduce.component/slave.components/trend/DayTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/MonthTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/WeekTrendPosts.slave.component.js
  src/utilities/api/TILog/posts.js
  src/utilities/hooks/index.js
  src/utilities/hooks/posts/useDayTrendPosts.js
  src/utilities/hooks/posts/useMonthTrendPosts.js
  src/utilities/hooks/posts/useTrendPosts.js
  src/utilities/hooks/posts/useWeekTrendPosts.js
Labels: bug

#63 Modify 메인디자인 수정, 스켈레톤 추가
  src/Components/Introduce.component/slave.components/postCard.component/postRank.slave.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRankSkeleton.slave.component.js
  src/Components/Introduce.component/slave.components/trend/DayTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/MonthTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/WeekTrendPosts.slave.component.js
Labels: enhancement

#64 배포 테스트
  .circleci/config.yml
  .circleci/scripts/envSettings.txt
  .circleci/scripts/generate-env-files.sh
  package.json
Labels: enhancement

#65 Fix 잘못된 Build 경로
  .circleci/config.yml
Labels: enhancement

#66 Fix bucket-name Error
  .circleci/config.yml
Labels: enhancement

#68 T il 220
  src/Components/Introduce.component/slave.components/trend/DayTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/MonthTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/WeekTrendPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/utilities/api/TILog/core/index.js
  src/utilities/api/TILog/posts.js
  src/utilities/api/github-stats/core/index.js
  src/utilities/hooks/posts/useDayTrendPosts.js
  src/utilities/hooks/posts/useMonthTrendPosts.js
  src/utilities/hooks/posts/useViewCursorPost.js
  src/utilities/hooks/posts/useWeekTrendPosts.js
Labels: bug, enhancement

#71 다크모드
  public/css/style.css
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Header.component/slave.components/UserBlog.slave.component.js
  src/Components/Introduce.component/Introduce.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRank.slave.component.js
  src/Components/Introduce.component/slave.components/postCard.component/postRankSkeleton.slave.component.js
  src/Components/Introduce.component/slave.components/trend/DayTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/MonthTrendPosts.slave.component.js
  src/Components/Introduce.component/slave.components/trend/WeekTrendPosts.slave.component.js
  src/Components/PostComment.component/PostComment.component.js
  src/Components/PostComment.component/slave.components/Comments/Comments.slave.component.js
  src/Components/PostComment.component/slave.components/Comments/InputComment.slave.component.js
  src/Components/PostComment.component/slave.components/Icons/CommentIcons.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/InputReply.slave.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostCreate.component/PostCreate.component.js
  src/Components/PostCreate.component/slave.components/AddStopModal.slave.component.js
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
  src/Components/PostDetail.component/slave.components/Article.slave.component.js
  src/Components/PostDetail.component/slave.components/LikeButton/LikeButton.slave.component.js
  src/Components/PostDetail.component/slave.components/MarkdownViewer/MarkdownViewer.slave.component.js
  src/Components/PostDetail.component/slave.components/Skeleton/ArticleSkeleton.slave.component.js
  src/Components/PostDetail.component/slave.components/Title/Title.slave.component.js
  src/Components/PostModify.component/PostModify.component.js
  src/Components/PostModify.component/slave.components/AddStopModal.slave.component.js
  src/Components/PostModify.component/slave.components/Editor.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
  src/Components/UserBlog.component/slave.components/PinnedRepo/UserPinnedRepo.slave.component.js
  src/Components/UserBlog.component/slave.components/ProfileCard/UserStats.slave.component.js
  src/Components/UserBlog.component/slave.components/RecentPosts/RecentPosts.slave.component.js
  src/Components/UserBlog.component/slave.components/Skeleton/StatsSkeleton.slave.component.js
  src/Components/UserBlog.component/slave.components/Stats.slave.component.js
  src/Components/UserBlog.component/slave.components/TopLanguage/UserTopLanguage.slave.component.js
  src/utilities/api/TILog/core/index.js
Labels: enhancement

#73 Fix 모바일 에러 대응
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostCreate.component/slave.components/AddStopModal.slave.component.js
  src/Components/PostModify.component/slave.components/AddStopModal.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
Labels: bug

#74 Fix 모바일 레이아웃 대응 배포
  src/Components/Header.component/slave.components/PostDetail.salve.component.js
  src/Components/Introduce.component/Introduce.component.js
  src/Components/PostComment.component/slave.components/Replies/Replies.slave.component.js
  src/Components/PostCreate.component/slave.components/AddStopModal.slave.component.js
  src/Components/PostModify.component/slave.components/AddStopModal.slave.component.js
  src/Components/ProfileDropdown.component/ProfileDropdown.component.js
Labels: bug

#75 Til 225 에디터 하이퍼링크 기능 추가
  package.json
  src/Components/PostCreate.component/slave.components/Editor.slave.component.js
  src/Components/PostDetail.component/slave.components/MarkdownViewer/MarkdownViewer.slave.component.js
  src/Components/PostModify.component/slave.components/Editor.slave.component.js
  yarn.lock
Labels: enhancement

#77 Add 카테고리 아이콘 리스트 추가
  src/Components/PostDetail.component/slave.components/Title/Title.slave.component.js
  src/Components/Utility.components/TechIconList.js
Labels: enhancement
